// <auto-generated />
namespace Final_Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class ConfirmationToken : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ConfirmationToken));
        
        string IMigrationMetadata.Id
        {
            get { return "201404162055420_ConfirmationToken"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
