// <auto-generated />
namespace Final_Project.Migrations.ConfigurationContext1
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class ada : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ada));
        
        string IMigrationMetadata.Id
        {
            get { return "201404221633026_ada"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
