// <auto-generated />
namespace Final_Project.Migrations.ConfigurationContext5
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class PhotoPath : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PhotoPath));
        
        string IMigrationMetadata.Id
        {
            get { return "201404251107112_PhotoPath"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
