// <auto-generated />
namespace Final_Project.Migrations.ConfigurationContext1
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class TwoMore : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TwoMore));
        
        string IMigrationMetadata.Id
        {
            get { return "201404211212002_TwoMore"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
